### ISSUE TITLE
Error when trying to logion with facebook,Failed to manipulate with MiniMagick

### ISSUE THREAD

**Issue by cromatom** [catarse/catarse#1355]
i get this error when trying to log in with facebook
i have installed imagemagick in ubuntu server

ActiveRecord::RecordInvalid in OmniauthCallbacksController#facebook
A validação falhou: Uploaded image Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: ImageMagick/GraphicsMagick is not installed

Extracted source (around line #8):
6
7
8
9
10
11
          

    def self.create_from_hash(hash)
      create!(
        {
          name: hash['info']['name'],
          email: hash['info']['email'],

Rails.root: /home/delta/catarse

Application Trace | Framework Trace | Full Trace
app/models/concerns/user/omniauth_handler.rb:8:in `create_from_hash'
app/models/authorization.rb:18:in `create_from_hash'
app/controllers/omniauth_callbacks_controller.rb:10:in `block (2 levels) in add_providers'
Request

Parameters:

{"code"=>"AQAyXx4vi4jQA0VmKGZ4JVKc5J5EaTnCRkJBrRQdqPDs5gIB7JS5BYxlSSL_y6LTJ8MnjCTwKdm0JKhMfFm4pOwy3dD-Gw59gY8TykGPlfOxLfB7lj5D6rzk_JGo8ejsy-8s_W90wtqsG6OepS3LDxmR1U6q23BX9D-DaHe4Y8kYbgi7XjgEtxGFNhJ6mNBeDNbE8mPfzTq06xirEY6Ef1OQVCtnhMG3d8Od1rpzpLy1mZj-XISbZ3ECO1QkKvtDB1ZFeaJtbfmIbyVEC_9QMYJHBTaQRsXCHiabmL3q0fCPtsQD7XpuowGQyRcfXz1ELcaXFQW64gJ6RzubhQd-nwMj",
 "state"=>"4eee5bd1e57cb301638c09dcb09f98687654673d3e91cb14"}
Toggle session dump
Toggle env dump
Response

Headers:

None

**Comment by cromatom** [comment]
gem install rmagick mini_magick

fixed
