### ISSUE TITLE
Install issues on  `PG::UndefinedFile: ERROR` ,   `pg_trgm.control`  No such file or directory

### ISSUE THREAD

**Issue by yreme** [catarse/catarse#1802]
`rake db:migrate` reports error , under  `ubuntu 15.04` and `postgresql 9.3`: 
```bash
$ rake db:migrate
.....
ALTER TABLE ONLY users
    ADD CONSTRAINT users_primary_user_id_reference FOREIGN KEY (primary_user_id) REFERENCES users(id);
--
-- PostgreSQL database dump complete
.....
PG::UndefinedFile: ERROR:  could not open extension control file "/usr/share/pgsql/extension/pg_trgm.control": No such file or directory

/home/em/.rvm/gems/ruby-2.2.3/gems/rack-mini-profiler-0.9.7/lib/patches/db/pg.rb:90:in `exec'
/home/em/.rvm/gems/ruby-2.2.3/gems/rack-mini-profiler-0.9.7/lib/patches/db/pg.rb:90:in `async_exec'
.....
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
In fact `/usr/share/pgsql/extension/pg_trgm.control` exist , because:
```ruby
$ ls /usr/share/pgsql/extension/pg_trgm.control
/usr/share/pgsql/extension/pg_trgm.control
```

Besides,  `bundle install` and `rake db:create` works , and could connect to `postgresql ` database.

What is wrong?  Would you please give me some direction on how to install it?

**Comment by devton** [comment]
hello @yreme you need to use postgresql 9.4 to run
