### ISSUE TITLE
Routing error

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse#2425]
When I visit the link `http://localhost:3000/projects/4/edit#basics` I get an err `ActionController::RoutingError (No route matches [GET] "/projects/4/null"):` . i looked into the code and found out that the route was pointing to edit method in the project controller but there was no edit method in that controller. Any idea? or do I have to create that edit method?

**Comment by sushantbajra** [comment]
Any lead in this one?

**Comment by vicnicius** [comment]
@sushant12 project edition endpoints should render this template: 
https://github.com/catarse/catarse/blob/master/app/views/catarse_bootstrap/projects/edit.html.slim, so you shouldn't need to write an `edit` controller. The error states that there isn't a null project controller, and sure there isn't. Perhaps a javascript issue might be making the page request this endpoint. 

Could you describe the steps you took to reproduce the bug? Does it happen when you are trying to access the page in all ways (clicking on the menu, going to the endpoint directly, etc.)?

**Comment by sushant12** [comment]
@vicnicius  
Log in, create a campaign,then I clicked on basic tab. That`s when I get that error

**Comment by sushantbajra** [comment]
@vicnicius were u able to reproduce it?

**Comment by vicnicius** [comment]
@sushantbajra unfortunately I wasn't. Tried on a fresh install on a virtual ubuntu 14.04 machine but couldn't reproduce. Would you be able to show us the network and console logs of your browser on the moment this error occurs?

**Comment by sushant12** [comment]
@vicnicius here is the log from console at the time of err. Let me know if you need more detail

```
Started GET "/projects/6/null" for 127.0.0.1 at 2016-12-22 08:22:11 +0545

ActionController::RoutingError (No route matches [GET] "/projects/6/null"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  web-console (3.3.0) lib/web_console/middleware.rb:131:in `call_app'
  web-console (3.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (3.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (3.3.0) lib/web_console/middleware.rb:18:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  thin (1.7.0) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.7.0) lib/thin/connection.rb:84:in `catch'
  thin (1.7.0) lib/thin/connection.rb:84:in `pre_process'
  thin (1.7.0) lib/thin/connection.rb:53:in `process'
  thin (1.7.0) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run_machine'
  eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run'
  thin (1.7.0) lib/thin/backends/base.rb:73:in `start'
  thin (1.7.0) lib/thin/server.rb:162:in `start'
  rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.7.1) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.7.1) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.7.1) lib/rails/commands/commands_tasks.rb:75:in `tap'
  railties (4.2.7.1) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.7.1) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.7.1) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<main>'


  Rendered /home/sushant/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (85.5ms)
  Rendered /home/sushant/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/routes/_route.html.erb (79.7ms)
  Rendered /home/sushant/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/routes/_route.html.erb (1.9ms)
  Rendered /home/sushant/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/routes/_route.html.erb (0.6ms)
  Rendered /home/sushant/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/routes/_route.html.erb (6.4ms)
  Rendered /home/sushant/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/routes/_route.html.erb (4.8ms)
  Rendered /home/sushant/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/routes/_table.html.erb (3.0ms)
  Rendered /home/sushant/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (50.9ms)
  Rendered /home/sushant/.rvm/gems/ruby-2.3.1/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (402.9ms)
```

**Comment by sushant12** [comment]
![screenshot-area-2016-12-22-082629](https://cloud.githubusercontent.com/assets/8981250/21413576/69fcc2b0-c820-11e6-9855-aaa02ae9ec1e.png)

**Comment by sushantbajra** [comment]
@vicnicius hi, any leads?

**Comment by sushantbajra** [comment]
@vicnicius ,I am only facing that issue on my linux machine (linux mint) but not  on my mac siera

**Comment by sushant12** [comment]
I am using docker to run the application so I am closing this issue for now

**Comment by vicnicius** [comment]
Hello @sushantbajra. It looks like it is a browser specific issue. Could you check what are those 2 errors shown on your browser inspector? You could also try to debug the catarse.js application, after making sure you are running it from our latest release (right now it is 1.0.21). The component that is probably leading to this bug is https://github.com/catarse/catarse.js/blob/2c9dee0174af3b881c11b7e8c3b2c21c94d9409d/src/c/project-dashboard-menu.js.

**Comment by sushant12** [comment]
This error only occurs when I change the `default_locale` of `config/initializers/locale.r`b to `en`
