### ISSUE TITLE
trying to create a project requires valid PagarMe api_key

### ISSUE THREAD

**Issue by mikesmayer** [catarse/catarse#2528]
I'm trying to identify where the call to Pagarme is taking place -- but when I try to create a project in my terminals its failing because I don't have a valid api_key saved in my CatarseSettings.

I'm struggling to figure out where this is taking place -- that is probably one of the few remaining dependencies that should be pushed into the payment engine.

I see that you have a pagarme key in the spec_helper.rb

DEBUG -- : Planting Project with sprig_id 1
ERROR -- : There was an error saving Project with sprig_id 1.
ERROR -- : #<Sprig::Seed::Record:0x007fe3c35de220>
ERROR -- : {:"user.bank_account"=>["can't be blank"]}
DEBUG -- : Planting BankAccount with sprig_id 1

rake aborted!

NoMethodError: undefined method `errors' for #<PagarMe::RequestError:0x007fe3c2eb2190>

/Users/mayer/.rbenv/versions/2.3.1/gemsets/citizensupported/gems/catarse_pagarme-2.10.6/app/models/catarse_pagarme/bank_account_concern.rb:26:in `rescue in pagarme_errors'
/Users/mayer/.rbenv/versions/2.3.1/gemsets/citizensupported/gems/catarse_pagarme-2.10.6/app/models/catarse_pagarme/bank_account_concern.rb:21:in `pagarme_errors'
/Users/mayer/.rbenv/versions/2.3.1/gemsets/citizensupported/gems/catarse_pagarme-2.10.6/app/models/catarse_pagarme/bank_account_concern.rb:9:in `must_be_valid_on_pagarme'

**Comment by adrianob** [comment]
The validation comes from here: https://github.com/catarse/catarse_pagarme/blob/master/app/models/catarse_pagarme/bank_account_concern.rb#L6

**Comment by mikesmayer** [comment]
and I see that you're calling the bank_account_concern.rb inside of the class BankAccount

'''
class BankAccount < ActiveRecord::Base
  include CatarsePagarme::BankAccountConcern
'''

so the questions I have are:
a. does the bank account need to be built & validated at this point in the lifecycle of when a user creates a project?

b. if we need to stick with creating a bank_account and validating it this early in the life of a project, is there a way to make the line:

'''
include CatarsePagarme::BankAccountConcern
'''
more generic so whatever payment engine is used can be written to respond to provide this validation?

So something like this?

'''
include PaymentEngine::BankAccountConcern
'''

I guess there's some planning and steps that need to be taken to extract these dependencies...

**Comment by adrianob** [comment]
This is in our plans, but it might take a while before we get into it.. For the time being, it should be easy to generalize this validation, check out the payment engine handler: https://github.com/catarse/catarse/blob/master/app/models/concerns/payment/payment_engine_handler.rb
A PR would be welcomed.

**Comment by mikesmayer** [comment]
@sushant12, let's have a look at the payment_engine_handler.rb

**Comment by sushant12** [comment]
@mikesmayer sure lets do it

**Comment by NBrunoB** [comment]
I'm also trying to come up with a way to run tests / bypass the validation of the bank accounts. I have just installed the platform so haven't figured out the logic of the validation yet, would greatly appreciate some insight on how to do it!

**Comment by mikesmayer** [comment]
hey @NBrunoB,

the catarse team has a PR that should alleviate the bank account validation issue -- but it hasn't been merged into the master branch code base yet.

@adrianob can probably tell us when we might expect this to happen, but its a fantastic change by the awesome team behind the app.

if you want to learn more about how they've decoupled the bank account from the project creation workflow check it out here: https://github.com/catarse/catarse/pull/2596

my understanding is that they've introduced a user balance model which will be a cashflow ledger, but I have yet to closely examine the changes because it hasn't yet been merged.

this PR is based in part on this ticket: https://github.com/catarse/catarse/issues/2524

**Comment by luisofribeiro** [comment]
We have just merged this PR creating user balance https://github.com/catarse/catarse/pull/2665 into master. 

It must alleviate the bank account validation issue.

**Comment by sushant12** [comment]
thanks mate
