### ISSUE TITLE
I have an error

### ISSUE THREAD

**Issue by kim0051** [catarse/catarse#2777]
I have an error during install.

I don't know what should I do.

I will attach an error message
and system infromation as a attatchment file.

My english is not so good.
Please understand my bad manner in English.

==

Error:
Web application could not be started
Error ID:
c9ae1f80
Details:
There was an error while trying to load the gem 'typhoeus'.
Gem Load Error is: 
Backtrace for gem load error is:
/usr/local/rvm/gems/ruby-2.4.1/gems/ffi-1.9.14/lib/ffi/library.rb:277:in `attach'
/usr/local/rvm/gems/ruby-2.4.1/gems/ffi-1.9.14/lib/ffi/library.rb:277:in `attach_function'
/usr/local/rvm/gems/ruby-2.4.1/gems/ethon-0.9.1/lib/ethon/libc.rb:16:in `<module:Libc>'
/usr/local/rvm/gems/ruby-2.4.1/gems/ethon-0.9.1/lib/ethon/libc.rb:6:in `<module:Ethon>'
/usr/local/rvm/gems/ruby-2.4.1/gems/ethon-0.9.1/lib/ethon/libc.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.4.1/gems/ethon-0.9.1/lib/ethon.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.4.1/gems/typhoeus-1.1.0/lib/typhoeus.rb:2:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.3/lib/bundler/runtime.rb:82:in `require'
/usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.3/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `each'
/usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `block in require'
/usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `each'
/usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `require'
/usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.3/lib/bundler.rb:108:in `require'
/var/www/catarse/config/application.rb:9:in `<top (required)>'
/var/www/catarse/config/environment.rb:4:in `require'
/var/www/catarse/config/environment.rb:4:in `<top (required)>'
config.ru:8:in `require'
config.ru:8:in `block in <main>'
/usr/local/rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
/usr/local/rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.1.8/src/helper-scripts/rack-preloader.rb:110:in `eval'
/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.1.8/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.1.8/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.1.8/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.1.8/src/helper-scripts/rack-preloader.rb:29:in `<main>'
Bundler Error Backtrace:
 (Bundler::GemRequireError)
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.3/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `each'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `block in require'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `each'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `require'
  /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.3/lib/bundler.rb:108:in `require'
  /var/www/catarse/config/application.rb:9:in `<top (required)>'
  /var/www/catarse/config/environment.rb:4:in `require'
  /var/www/catarse/config/environment.rb:4:in `<top (required)>'
  config.ru:8:in `require'
  config.ru:8:in `block in <main>'
  /usr/local/rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.1.8/src/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.1.8/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.1.8/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.1.8/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.1.8/src/helper-scripts/rack-preloader.rb:29:in `<main>'

==
[System_information.txt](https://github.com/catarse/catarse/files/1292489/System_information.txt)

**Comment by vicnicius** [comment]
Hi, @kim0051! Your english is just fine, don't worry!

This error seem related to your environment. The typhoneus gem is a wrapper for curl, so maybe you don't have it available on your system. If that's the case, installing libcurl-dev should fix it `sudo apt-get install libcurl4-openssl-dev`.
